### ISSUE TITLE
running getallvms.py gets no output

### ISSUE THREAD

**Issue by tdubb123** [vmware/pyvmomi-community-samples#538] opened 2019-01-07 02:56 UTC
I install pyvmomi and tried to run the sample script against my vcenter but got no output. no error

sudo python getallvms.py -s vcenter_ip -u administrator@vsphere.local -p xxxxxxx

any idea?

I am on osX

**Comment by tdubb123** [comment] 2019-01-07 03:00
adding that I am using pyvmomi 6.7 and python 2.7

Name: pyvmomi
Version: 6.7.1.2018.12
Summary: VMware vSphere Python SDK
Home-page: https://github.com/vmware/pyvmomi
Author: VMware, Inc.
Author-email: jhu@vmware.com
License: License :: OSI Approved :: Apache Software License
Location: /Library/Python/2.7/site-packages
Requires: requests, six
Required-by:

**Comment by tdubb123** [comment] 2019-01-07 04:50
looks like I can run it if I specify my host IP but not vcenter. any idea why?

**Comment by pgbidkar** [comment] 2019-01-07 07:41
Hi @tdubb123 I Dont see this issue in my Test env. Please can you re-verify on more VC setup if you have?

**Comment by tdubb123** [comment] 2019-01-07 14:22
Hi

VC is vcsa 6.7 appliance

**Comment by pgbidkar** [comment] 2019-01-08 06:52
VC 6.7 also, I am not able to reproduce the issue. 
Please can you check with one more VC setup IP and confirm?
Thanks

**Comment by pgbidkar** [comment] 2019-01-14 06:56
Closing the issue. Not reproducible with 6.7VC.

**Closed by pgbidkar** 2019-01-14 06:56 UTC

**Comment by tdubb123** [comment] 2019-03-13 12:42
I am really not getting any output using my vcsa ip. Using esxi host ip is ok. why is that?

I just did brand new install with pip on osx


(venv) Tonys-MacBook-Pro:sample tonywong$ pip show pyvmomi
Name: pyvmomi
Version: 6.7.1.2018.12
Summary: VMware vSphere Python SDK
Home-page: https://github.com/vmware/pyvmomi
Author: VMware, Inc.
Author-email: jhu@vmware.com
License: License :: OSI Approved :: Apache Software License
Location: /Users/tonywong/PycharmProjects/untitled1/venv/lib/python3.7/site-packages
Requires: requests, six
Required-by: 
(venv) Tonys-MacBook-Pro:sample tonywong$ python --version
Python 3.7.2
